# Generated by Django 5.0.3 on 2025-05-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="artists/"),
        ),
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
